// src/shared/enums.js

export const MessageType = Object.freeze({
  // Popup -> Background
  GET_STATUS: "GET_STATUS",
  SAVE_SIGNAL_CONFIG: "SAVE_SIGNAL_CONFIG",
  START_MONITORING: "START_MONITORING",
  STOP_MONITORING: "STOP_MONITORING",
  EXPORT_CSV: "EXPORT_CSV",
  GET_LOGS: "GET_LOGS",

  // Background -> Content
  PROBE_CHART: "PROBE_CHART",
  START_STREAM: "START_STREAM",
  STOP_STREAM: "STOP_STREAM",
  REQUEST_CONTEXT: "REQUEST_CONTEXT",

  // Content -> Background
  CHART_DETECTED: "CHART_DETECTED",
  PLATFORM_INFO: "PLATFORM_INFO",
  SYMBOL_TIMEFRAME: "SYMBOL_TIMEFRAME",
  PRICE_UPDATE: "PRICE_UPDATE",
  CANDLE_UPDATE: "CANDLE_UPDATE",
  STREAM_ERROR: "STREAM_ERROR",

  // Background -> Popup
  STATUS_UPDATE: "STATUS_UPDATE",
  ENGINE_STATE_UPDATE: "ENGINE_STATE_UPDATE",
  TRADE_EVENT: "TRADE_EVENT",
  EXPORT_READY: "EXPORT_READY"
});

export const Direction = Object.freeze({
  LONG: "LONG",
  SHORT: "SHORT",
  AUTO: "AUTO"
});

export const EntryMode = Object.freeze({
  BREAKOUT_ONLY: "BREAKOUT_ONLY",
  BREAKOUT_RETEST: "BREAKOUT_RETEST"
});

export const EngineState = Object.freeze({
  IDLE: "IDLE",
  WAIT_BREAKOUT: "WAIT_BREAKOUT",
  WAIT_RETEST: "WAIT_RETEST",
  ENTRY_TRIGGER: "ENTRY_TRIGGER",
  TRADE_ACTIVE: "TRADE_ACTIVE",
  TP_HIT: "TP_HIT",
  SL_HIT: "SL_HIT",
  FALSE_BREAKOUT: "FALSE_BREAKOUT"
});
